
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    user: "2001:3004"
    ports:
      - "9000:9000"
    # environment:
      #  - UID=2001
      #  - GID=3004
      # - SONAR_JDBC_URL=jdbc:postgresql://192.168.1.53:5432/sonarqube
      # - SONAR_JDBC_USERNAME=sonarqube
      # - SONAR_JDBC_PASSWORD={{ENV_SONAR_JDBC_PASSWORD}}
    volumes:
      - /mnt/nfs_sonarqube/data:/opt/sonarqube/data
      - /mnt/nfs_sonarqube/logs:/opt/sonarqube/logs
      - /mnt/nfs_sonarqube/extensions:/opt/sonarqube/extensions
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    restart: unless-stopped
    networks:
      - homelab
volumes:
  sonarqube_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.53,rw,nolock,nfsvers=4
      device: :/mnt/RedFortress/portainer_apps/sonarqube/data
  sonarqube_logs:
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: addr=192.168.1.53,rw
    #   device: :/mnt/RedFortress/portainer_apps/sonarqube/logs
  sonarqube_extensions:
    # driver: local
    # driver_opts:
    #   type: nfs
    #   o: addr=192.168.1.53,rw
    #   device: :/mnt/RedFortress/portainer_apps/sonarqube/extensions
networks:
  homelab:
    driver: bridge